2019-07-18T13:57:47|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamMS\Selina_Contingency.py", line 300, in run
    for t in range(0, numtrials):
NameError: name 'numtrials' is not defined

